title: Dual Power Gathering Midwest
favicon: https://dpgmidwest.org/favicons/favicon.ico
logo: /images/logo-dark-shadow-line.png
card_image: /images/logo-dark-shadow-line.png
email: "midwestdualpower@protonmail.com"
SEOTitle: "Dual Power Gathering Midwest"
description: "2023 Dual Power Gathering in the midwest region (great lakes and great plains)"
url: "http://www.dpgmidwest.org"
domain: "dpgmidwest.org"
github_repo: "https://github.com/dpgmidwest/dpgmidwest.github.io"
featured-tags: False
featured-condition-size: 100
baseurl: ""
RSS: true
github_username: dpgmidwest
permalink: pretty
paginate: 3
paginate_path: "/:num/"
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: false
plugins: [jekyll-paginate, jekyll-seo-tag]
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
chrome-tab-theme-color: "#000000"
